# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
    ]

    operations = [
        migrations.CreateModel(
            name='LCRSPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('three_columns', wagtail.wagtailcore.blocks.StructBlock((('column_1_text', wagtail.wagtailcore.blocks.RichTextBlock()), ('column_1_link_url', wagtail.wagtailcore.blocks.StructBlock((('page', wagtail.wagtailcore.blocks.PageChooserBlock(required=False)), ('url', wagtail.wagtailcore.blocks.URLBlock(required=False))), required=False)), ('column_1_link_text', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('column_1_link_button', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('info', 'info'), ('warning', 'warning'), ('danger', 'danger'), ('success', 'success')], required=False)), ('column_2_text', wagtail.wagtailcore.blocks.RichTextBlock()), ('column_2_link_url', wagtail.wagtailcore.blocks.StructBlock((('page', wagtail.wagtailcore.blocks.PageChooserBlock(required=False)), ('url', wagtail.wagtailcore.blocks.URLBlock(required=False))), required=False)), ('column_2_link_text', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('column_2_link_button', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('info', 'info'), ('warning', 'warning'), ('danger', 'danger'), ('success', 'success')], required=False)), ('column_3_text', wagtail.wagtailcore.blocks.RichTextBlock()), ('column_3_link_url', wagtail.wagtailcore.blocks.StructBlock((('page', wagtail.wagtailcore.blocks.PageChooserBlock(required=False)), ('url', wagtail.wagtailcore.blocks.URLBlock(required=False))), required=False)), ('column_3_link_text', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('column_3_link_button', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('info', 'info'), ('warning', 'warning'), ('danger', 'danger'), ('success', 'success')], required=False)))))), default='')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
